name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci  # Cài đặt phụ thuộc từ package-lock.json để đảm bảo môi trường sạch sẽ

      - name: Give Jest executable permission
        run: chmod +x ./node_modules/.bin/jest  # Đảm bảo Jest có quyền thực thi

      - name: Run tests
        run: npx jest --passWithNoTests  # Thêm flag --passWithNoTests để bỏ qua lỗi nếu không có bài kiểm thử

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Đảm bảo chỉ triển khai khi nhánh chính (main) được cập nhật

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh  # Cài đặt Heroku CLI

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku main  # Triển khai lên Heroku
